# Generated by Django 5.2.1 on 2025-06-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_website_alter_product_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
