# Generated by Django 5.2.1 on 2025-06-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_variant_id',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
