# Generated by Django 5.2.1 on 2025-06-21 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_product_product_variant_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
    ]
