# Generated by Django 5.2.1 on 2025-06-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_googlesheetlinks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googlesheetlinks',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='googlesheetlinks',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetlinks',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetlinks',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetlinks',
            name='filename',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetlinks',
            name='processed_products',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='googlesheetlinks',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='googlesheetlinks',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='googlesheetlinks',
            name='total_products',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='googlesheetlinks',
            name='website_filter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
