# Generated by Django 5.2.1 on 2025-06-24 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_alter_googlesheetlinks_options_and_more'),
    ]

    operations = [
    ]
