# Generated by Django 5.2.1 on 2026-03-12 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_alter_product_category_alter_product_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.IntegerField(help_text='Vendor ID for website upload CSV')),
                ('sku_prefix', models.CharField(blank=True, default='', help_text="Prefix added to SKU (e.g., 'RLC-', 'IBSLA')", max_length=50)),
                ('markup_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage to adjust price (+/- %). Example: 15.00 for 15% markup', max_digits=5)),
                ('default_category_id', models.CharField(blank=True, default='', help_text='Default category ID for website', max_length=100)),
                ('default_product_type_id', models.CharField(blank=True, default='3', help_text='Default product type ID', max_length=100)),
                ('track_inventory', models.BooleanField(default=True, help_text='Default: Track inventory for this vendor')),
                ('sell_out_of_stock', models.BooleanField(default=True, help_text='Default: Allow selling when out of stock')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_config', to='scraper.website')),
            ],
            options={
                'verbose_name': 'Vendor Configuration',
                'verbose_name_plural': 'Vendor Configurations',
                'ordering': ['website__name'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_rows', models.IntegerField(default=0, help_text='Total rows in CSV')),
                ('processed_rows', models.IntegerField(default=0)),
                ('matched_products', models.IntegerField(default=0, help_text='Products matched in database')),
                ('new_products_found', models.IntegerField(default=0, help_text='Products in DB but not in import')),
                ('skipped_rows', models.IntegerField(default=0)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Website Import Log',
                'verbose_name_plural': 'Website Import Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_website', models.BooleanField(default=False, help_text='Is this product currently on the website?')),
                ('website_sku', models.CharField(blank=True, default='', help_text='SKU format as it appears on website (with prefix)', max_length=500)),
                ('website_product_id', models.CharField(blank=True, default='', help_text='Product ID from website export', max_length=100)),
                ('status', models.CharField(choices=[('new', 'New - Not on Website'), ('synced', 'Synced - On Website'), ('updated', 'Updated - Needs Re-sync'), ('removed', 'Removed from Website')], default='new', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last time this product was synced', null=True)),
                ('last_export_at', models.DateTimeField(blank=True, help_text='Last time included in export', null=True)),
                ('selected_for_export', models.BooleanField(default=False, help_text='Selected by user for next export')),
                ('custom_category_id', models.CharField(blank=True, default='', help_text='Override default category', max_length=100)),
                ('custom_price', models.CharField(blank=True, default='', help_text='Override scraped price', max_length=50)),
                ('custom_track_inventory', models.BooleanField(blank=True, help_text='Override default inventory tracking', null=True)),
                ('custom_sell_out_of_stock', models.BooleanField(blank=True, help_text='Override default out of stock selling', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_status', to='scraper.product')),
            ],
            options={
                'verbose_name': 'Product Sync Status',
                'verbose_name_plural': 'Product Sync Statuses',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['on_website'], name='scraper_pro_on_webs_0b19ab_idx'), models.Index(fields=['status'], name='scraper_pro_status_be23d2_idx'), models.Index(fields=['selected_for_export'], name='scraper_pro_selecte_8a5c8f_idx')],
            },
        ),
    ]
