# Generated by Django 5.2.1 on 2026-03-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0013_add_product_sync_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteimportlog',
            name='vendor_website',
            field=models.CharField(blank=True, default='', help_text='Vendor/website being compared', max_length=100),
        ),
    ]
