# Generated by Django 5.2.1 on 2026-03-15 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0013_add_sheet_file_id'),
        ('scraper', '0014_add_vendor_website_to_import_log'),
    ]

    operations = [
    ]
