# Generated by Django 5.2.1 on 2026-03-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0017_add_is_disabled_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsyncstatus',
            name='disabled_at',
        ),
        migrations.RemoveField(
            model_name='productsyncstatus',
            name='disabled_reason',
        ),
        migrations.RemoveField(
            model_name='websiteimportlog',
            name='unmatched_products',
        ),
        migrations.AlterField(
            model_name='googlesheetlinks',
            name='sheet_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productsyncstatus',
            name='is_disabled',
            field=models.BooleanField(default=False, help_text='disable for never sync'),
        ),
    ]
